baseURL = "https://chullepg.github.io/"
languageCode = "en-us"
title = "My Hugo Site with Notrack"
theme = "notrack"
enableRobotsTXT = true

[params]
  description = "This is a sample Hugo site with Notrack theme"
  author = "Your Name"

